# Dockerfile-nginx
FROM nginx:latest
# Nginx will listen on this port
EXPOSE 80
EXPOSE 443
# Remove the default config file that
# /etc/nginx/nginx.conf includes
RUN rm /etc/nginx/conf.d/default.conf

# We app.conf file as the new nginx configuration
COPY app.conf /etc/nginx/conf.d

ADD certs/apprenticeng.local.crt /etc/nginx/apprenticeng.local.crt
ADD certs/apprenticeng.local.key /etc/nginx/apprenticeng.local.key


